name: Render Block
on: 
  workflow_dispatch:
    inputs:
      textures_url:
        type: string
        required: true
      
jobs:
  render:
    runs-on: ubuntu-latest
    env:
      TEXTURES: ${{ inputs.textures_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: |
          curl -o input/textures.zip $TEXTURES
          unzip input/textures.zip
          bash render.sh input/ output/
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: output
