name: Render Block
on: 
  workflow_dispatch:
    inputs:
      textures_url:
        type: string
        required: true
      
jobs:
  render:
    runs-on: ubuntu-latest
    env:
      TEXTURES: ${{ inputs.textures_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: |
          mkdir input
          curl -o textures.zip $TEXTURES
          unzip textures.zip -d /input
          bash render.sh input/ output/
      - uses: actions/upload-artifact@v4
        with:
          name: Icon
          path: output/
