name: Render Block
on: 
  workflow_dispatch:
    inputs:
      texture_url:
        type: string
        required: true
      
jobs:
  render:
    runs-on: ubuntu-latest
    env:
      PACK: ${{ inputs.resources_pack_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Run
        run: |
          bash render.sh input/ output/
